### ISSUE TITLE
Customize email sent submission starts

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-infra#26]
Here is the current email:

```
From: <nlp-sandbox-bot@synapse.org>
Date: Fri, Jun 25, 2021 at 3:11 AM
Subject: Submission Processing Started in NLP sandbox - Id Annotator (9614797)
To: <thomas.schaffter@xxx>


Dear NLP Sandbox Bots:

Your submission (submission ID 9712510) is in progress. Log files produced while your workflow is running will be periodically uploaded here: https://www.synapse.org/#!Synapse:syn25920738 Further notification will be provided when it is complete.

Sincerely,

Submission Queue Administration
```

Comments:
- Submitters probably don't know what "workflow" refers to.
- We probably don't want submitters to respond to this email. A solution could be to include a sentence to let them know how to contact us when they have a question or want to report a bug.
- Sign the email with "NLP Sandbox Bot"
- Maybe say something about log per data site and why they may not be available (private dataset)

@thomasyu888 Let me know if we have the opportunity to customize the message. If yes, I'll draft the new message template.

**Comment by thomasyu888** [comment]
@tschaffter the email is not customizable.

**Comment by tschaffter** [comment]
@thomasyu888 I think that you created another ticket where you invited me to submit the test for an email sent when the submission starts running. Is that correct? If yes, can you remind me where this ticket lives?

**Comment by thomasyu888** [comment]
Closing as there is a new ticket: https://github.com/nlpsandbox/nlpsandbox-controller/issues/129
